<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_bringup</name>
  <version>2.1.4</version>
  <description>
    ROS 2 launch scripts for starting the robot
  </description>
  <maintainer email="willson@robotis.com">Will Son</maintainer>
  <license>Apache 2.0</license>
  <url type="website">http://turtlebot3.robotis.com</url>
  <url type="repository">https://github.com/ROBOTIS-GIT/turtlebot3</url>
  <url type="bugtracker">https://github.com/ROBOTIS-GIT/turtlebot3/issues</url>
  <author email="thlim@robotis.com">Darby Lim</author>
  <author email="pyo@robotis.com">Pyo</author>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>aid_robot_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>nav2_map_server</depend>
  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>lightning</depend>
  <exec_depend>g1_nav_bridge</exec_depend>
  <exec_depend>aid_navigation2</exec_depend>
  <exec_depend>aid_robot_py</exec_depend>
  <exec_depend>nav2_collision_monitor</exec_depend>
  <exec_depend>livox_ros_driver2</exec_depend>
  <exec_depend>point_filter</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>usb_cam</exec_depend>
  <exec_depend>hls_lfcd_lds_driver</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
